from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_windowMain(object):
    def setupUi(self, windowMain):
        windowMain.setObjectName("windowMain")
        windowMain.resize(915, 540)
        self.tabWidget = QtWidgets.QTabWidget(parent=windowMain)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 395, 540))
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.plotTab = QtWidgets.QWidget()
        self.plotTab.setObjectName("plotTab")
        self.yInd = QtWidgets.QLabel(parent=self.plotTab)
        self.yInd.setGeometry(QtCore.QRect(20, 10, 60, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yInd.setFont(font)
        self.yInd.setObjectName("yInd")
        self.funcEdit = QtWidgets.QLineEdit(parent=self.plotTab)
        self.funcEdit.setGeometry(QtCore.QRect(60, 10, 320, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.funcEdit.setFont(font)
        self.funcEdit.setObjectName("funcEdit")
        self.btnPlot = QtWidgets.QPushButton(parent=self.plotTab)
        self.btnPlot.setGeometry(QtCore.QRect(10, 60, 370, 39))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnPlot.setFont(font)
        self.btnPlot.setObjectName("btnPlot")
        self.btnClear = QtWidgets.QPushButton(parent=self.plotTab)
        self.btnClear.setGeometry(QtCore.QRect(10, 110, 370, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.funcList = QtWidgets.QListWidget(parent=self.plotTab)
        self.funcList.setGeometry(QtCore.QRect(10, 160, 370, 340))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.funcList.setFont(font)
        self.funcList.setObjectName("funcList")
        self.tabWidget.addTab(self.plotTab, "")
        self.saveTab = QtWidgets.QWidget()
        self.saveTab.setObjectName("saveTab")
        self.tabWidget.addTab(self.saveTab, "")
        self.canvasL = QtWidgets.QLabel(parent=windowMain)
        self.canvasL.setGeometry(QtCore.QRect(405, 25, 500, 500))
        self.canvasL.setText("")
        self.canvasL.setObjectName("canvasL")

        self.retranslateUi(windowMain)
        self.tabWidget.setCurrentIndex(0)
        self.funcList.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(windowMain)

    def retranslateUi(self, windowMain):
        _translate = QtCore.QCoreApplication.translate
        windowMain.setWindowTitle(_translate("windowMain", "Form"))
        self.yInd.setText(_translate("windowMain", "y  ="))
        self.btnPlot.setText(_translate("windowMain", "Построить"))
        self.btnClear.setText(_translate("windowMain", "Очистить"))
        self.funcList.setSortingEnabled(False)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plotTab), _translate("windowMain", "Plotting"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.saveTab), _translate("windowMain", "Saving"))
