from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowMain(object):
    def setupUi(self, windowMain):
        windowMain.setObjectName("windowMain")
        windowMain.resize(900, 520)
        self.btnPlot = QtWidgets.QPushButton(parent=windowMain)
        self.btnPlot.setGeometry(QtCore.QRect(10, 60, 370, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnPlot.setFont(font)
        self.btnPlot.setObjectName("btnPlot")
        self.btnClear = QtWidgets.QPushButton(parent=windowMain)
        self.btnClear.setGeometry(QtCore.QRect(10, 110, 370, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.funcList = QtWidgets.QListWidget(parent=windowMain)
        self.funcList.setGeometry(QtCore.QRect(10, 159, 370, 350))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.funcList.setFont(font)
        self.funcList.setObjectName("funcList")
        self.funcEdit = QtWidgets.QLineEdit(parent=windowMain)
        self.funcEdit.setGeometry(QtCore.QRect(60, 10, 320, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.funcEdit.setFont(font)
        self.funcEdit.setObjectName("funcEdit")
        self.yInd = QtWidgets.QLabel(parent=windowMain)
        self.yInd.setGeometry(QtCore.QRect(20, 10, 60, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yInd.setFont(font)
        self.yInd.setObjectName("yInd")
        self.canvasL = QtWidgets.QLabel(parent=windowMain)
        self.canvasL.setGeometry(QtCore.QRect(390, 10, 500, 500))
        self.canvasL.setText("")
        self.canvasL.setObjectName("canvasL")

        self.retranslateUi(windowMain)
        self.funcList.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(windowMain)

    def retranslateUi(self, windowMain):
        _translate = QtCore.QCoreApplication.translate
        windowMain.setWindowTitle(_translate("windowMain", "Graphical calculator"))
        self.btnPlot.setText(_translate("windowMain", "Построить"))
        self.btnClear.setText(_translate("windowMain", "Очистить"))
        self.funcList.setSortingEnabled(False)
        self.yInd.setText(_translate("windowMain", "y  ="))

