# Form implementation generated from reading ui file 'proWin.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_proWin(object):
    def setupUi(self, proWin):
        proWin.setObjectName("proWin")
        proWin.resize(400, 465)
        font = QtGui.QFont()
        font.setPointSize(12)
        proWin.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=proWin)
        self.centralwidget.setObjectName("centralwidget")
        self.imgLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.imgLabel.setGeometry(QtCore.QRect(136, 20, 128, 128))
        self.imgLabel.setObjectName("imgLabel")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 81, 31))
        self.label_2.setObjectName("label_2")
        self.nameLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(140, 160, 231, 31))
        self.nameLabel.setObjectName("nameLabel")
        self.backToMainButt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.backToMainButt.setGeometry(QtCore.QRect(30, 210, 341, 51))
        self.backToMainButt.setObjectName("backToMainButt")
        self.leaveProphileButt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.leaveProphileButt.setGeometry(QtCore.QRect(30, 300, 341, 51))
        self.leaveProphileButt.setObjectName("leaveProphileButt")
        self.deleteProphileButt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteProphileButt.setGeometry(QtCore.QRect(30, 390, 341, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        self.deleteProphileButt.setPalette(palette)
        self.deleteProphileButt.setDefault(True)
        self.deleteProphileButt.setObjectName("deleteProphileButt")
        proWin.setCentralWidget(self.centralwidget)

        self.retranslateUi(proWin)
        QtCore.QMetaObject.connectSlotsByName(proWin)

    def retranslateUi(self, proWin):
        _translate = QtCore.QCoreApplication.translate
        proWin.setWindowTitle(_translate("proWin", "MainWindow"))
        self.imgLabel.setText(_translate("proWin", "Картинка"))
        self.label_2.setText(_translate("proWin", "Имя:"))
        self.nameLabel.setText(_translate("proWin", "Base name"))
        self.backToMainButt.setText(_translate("proWin", "Вернуться к графу"))
        self.leaveProphileButt.setText(_translate("proWin", "Выйти из аккаунта"))
        self.deleteProphileButt.setText(_translate("proWin", "Удалить аккаунт"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    proWin = QtWidgets.QMainWindow()
    ui = Ui_proWin()
    ui.setupUi(proWin)
    proWin.show()
    sys.exit(app.exec())
