# Form implementation generated from reading ui file 'varsWin.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_varsWin(object):
    def setupUi(self, varsWin):
        varsWin.setObjectName("varsWin")
        varsWin.resize(695, 546)
        self.centralwidget = QtWidgets.QWidget(parent=varsWin)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 661, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 180, 661, 301))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.varsList = QtWidgets.QListWidget(parent=self.horizontalLayoutWidget_2)
        self.varsList.setObjectName("varsList")
        self.horizontalLayout_2.addWidget(self.varsList)
        self.funcsList = QtWidgets.QListWidget(parent=self.horizontalLayoutWidget_2)
        self.funcsList.setObjectName("funcsList")
        self.horizontalLayout_2.addWidget(self.funcsList)
        self.addVarButt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addVarButt.setGeometry(QtCore.QRect(20, 120, 151, 41))
        self.addVarButt.setObjectName("addVarButt")
        self.delVarButt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delVarButt.setGeometry(QtCore.QRect(180, 120, 161, 41))
        self.delVarButt.setObjectName("delVarButt")
        self.addFuncButt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addFuncButt.setGeometry(QtCore.QRect(360, 120, 141, 41))
        self.addFuncButt.setObjectName("addFuncButt")
        self.delFuncButt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delFuncButt.setGeometry(QtCore.QRect(510, 120, 171, 41))
        self.delFuncButt.setObjectName("delFuncButt")
        self.leaveToMainButt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.leaveToMainButt.setGeometry(QtCore.QRect(20, 490, 661, 51))
        self.leaveToMainButt.setObjectName("leaveToMainButt")
        varsWin.setCentralWidget(self.centralwidget)

        self.retranslateUi(varsWin)
        QtCore.QMetaObject.connectSlotsByName(varsWin)

    def retranslateUi(self, varsWin):
        _translate = QtCore.QCoreApplication.translate
        varsWin.setWindowTitle(_translate("varsWin", "MainWindow"))
        self.label.setText(_translate("varsWin", "Переменные"))
        self.label_2.setText(_translate("varsWin", "Функции"))
        self.addVarButt.setText(_translate("varsWin", "Добавить переменную"))
        self.delVarButt.setText(_translate("varsWin", "Удалить переменную"))
        self.addFuncButt.setText(_translate("varsWin", "Добавить функцию"))
        self.delFuncButt.setText(_translate("varsWin", "Удалить функцию"))
        self.leaveToMainButt.setText(_translate("varsWin", "Вернуться к графу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    varsWin = QtWidgets.QMainWindow()
    ui = Ui_varsWin()
    ui.setupUi(varsWin)
    varsWin.show()
    sys.exit(app.exec())
